import { Blog } from "@/types/blog";

const blogData: Blog[] = [
  {
    id: "1",
    title: "How to Improve Website SEO in 2024",
    video: "",
    thumbnail: "/images/seo-blog.jpg",
    paragraph: "Discover the best SEO strategies to rank higher on Google in 2024...",
    tags: ["SEO", "Marketing"],
    publishDate: "2024-02-12",
    author: {
      name: "John Doe",
      designation: "SEO Expert",
      image: "/images/blog/author-01.png",
    },
  },
  {
    id: "2",
    title: "Why Responsive Design Matters for SEO",
    video: "",
    thumbnail: "/images/responsive-design.jpg",
    paragraph: "A mobile-friendly website is key to better search rankings and user experience...",
    tags: ["Web Design", "SEO"],
    publishDate: "2024-02-15",
    author: {
      name: "Jane Smith",
      designation: "Web Designer",
      image: "/images/blog/author-02.png",
    },
  },
  {
    id: "3",
    title: "Top Web Design Trends for 2024",
    video: "",
    thumbnail: "/images/web-design-trends.jpg",
    paragraph: "Stay ahead of the competition with the latest website design trends...",
    tags: ["Web Design", "UI/UX"],
    publishDate: "2024-02-18",
    author: {
      name: "Robert Brown",
      designation: "UI/UX Designer",
      image: "/images/blog/author-03.png",
    },
  },
  {
    id: "4",
    title: "The Importance of Fast-Loading Websites",
    video: "",
    thumbnail: "/images/page-speed.jpg",
    paragraph: "Speed matters! Learn how website performance affects SEO and conversions...",
    tags: ["Performance", "SEO"],
    publishDate: "2024-02-20",
    author: {
      name: "Emily Davis",
      designation: "Performance Analyst",
      image: "/images/blog/author-04.png",
    },
  },
  {
    id: "5",
    title: "How Digital Marketing Can Grow Your Business",
    video: "",
    thumbnail: "/images/digital-marketing.jpg",
    paragraph: "From social media to SEO, digital marketing is the future of business growth...",
    tags: ["Marketing", "Strategy"],
    publishDate: "2024-02-22",
    author: {
      name: "Michael Johnson",
      designation: "Digital Marketer",
      image: "/images/blog/author-05.png",
    },
  },
  {
    id: "6",
    title: "The Role of UI/UX in Website Conversion Rates",
    video: "",
    thumbnail: "/images/uiux-conversion.jpg",
    paragraph: "Great design is more than aesthetics – it's about boosting conversions...",
    tags: ["UI/UX", "Conversion"],
    publishDate: "2024-02-25",
    author: {
      name: "Sophia Martinez",
      designation: "UX Researcher",
      image: "/images/blog/author-06.png",
    },
  },
  {
    id: "7",
    title: "Best E-Commerce Website Design Practices",
    video: "",
    thumbnail: "/images/ecommerce-design.jpg",
    paragraph: "Turn visitors into customers with an optimized e-commerce website...",
    tags: ["E-Commerce", "Web Design"],
    publishDate: "2024-02-28",
    author: {
      name: "Daniel Wilson",
      designation: "E-Commerce Specialist",
      image: "/images/blog/author-07.png",
    },
  },
  {
    id: "8",
    title: "How Blogging Helps Your Website's SEO",
    video: "",
    thumbnail: "/images/blogging-seo.jpg",
    paragraph: "Consistent blogging can drive organic traffic and improve rankings...",
    tags: ["SEO", "Content Marketing"],
    publishDate: "2024-03-01",
    author: {
      name: "Olivia Thomas",
      designation: "Content Strategist",
      image: "/images/blog/author-08.png",
    },
  },
  {
    id: "9",
    title: "Effective Call-to-Action Strategies for Websites",
    video: "",
    thumbnail: "/images/cta-strategies.jpg",
    paragraph: "Maximize user engagement with powerful CTAs on your site...",
    tags: ["Marketing", "Conversion"],
    publishDate: "2024-03-03",
    author: {
      name: "James Lee",
      designation: "Marketing Consultant",
      image: "/images/blog/author-09.png",
    },
  },
  {
    id: "10",
    title: "Local SEO: How to Rank Higher in Your City",
    video: "",
    thumbnail: "/images/local-seo.jpg",
    paragraph: "Local SEO is essential for businesses targeting nearby customers...",
    tags: ["SEO", "Local Marketing"],
    publishDate: "2024-03-05",
    author: {
      name: "Emma Garcia",
      designation: "Local SEO Expert",
      image: "/images/blog/author-10.png",
    },
  }
];

export default blogData;
