import { Blog } from "@/types/blog";

const blogData: Blog[] = [
  {
    id: '1',
    title: "Exploring the Future of AI",
    video: "/video/blog/blog-1.mp4",
    paragraph: "Cloud computing has revolutionized data storage...",
    tags: ["AI"],
    publishDate: "2024-12-01",
    author: {
      name: "John Doe",
      designation: "Tech Writer",
      image: "/images/blog/author-01.png",
    },
  },
  {
    id: 2,
    title: "The Rise of Quantum Computing",
    video: "/video/blog/blog-1.mp4",
    paragraph: "Quantum computing is set to change the world...",
    tags: ["Quantum", "Technology"],
    publishDate: "2024-12-02",
    author: {
      name: "Alice Smith",
      designation: "Computer Scientist",
      image: "/images/blog/author-02.png",
    },
  },
  {
    id: 3,
    title: "Cybersecurity in the Digital Age",
    video: "/video/blog/blog-1.mp4",
    paragraph: "With rising cyber threats, security is paramount...",
    tags: ["Cybersecurity"],
    publishDate: "2024-12-03",
    author: {
      name: "Robert Brown",
      designation: "Cybersecurity Expert",
      image: "/images/blog/author-03.png",
    },
  },
  {
    id: 4,
    title: "Blockchain Beyond Cryptocurrency",
    video: "/video/blog/blog-1.mp4",
    paragraph: "Blockchain is more than just Bitcoin...",
    tags: ["Blockchain"],
    publishDate: "2024-12-04",
    author: {
      name: "Emily Davis",
      designation: "Blockchain Analyst",
      image: "/images/blog/author-04.png",
    },
  },
  {
    id: 5,
    title: "The Role of IoT in Smart Cities",
    video: "/video/blog/blog-1.mp4",
    paragraph: "IoT is driving innovation in smart city infrastructure...",
    tags: ["IoT", "Smart Cities"],
    publishDate: "2024-12-05",
    author: {
      name: "Michael Johnson",
      designation: "IoT Engineer",
      image: "/images/blog/author-05.png",
    },
  },
  {
    id: 6,
    title: "Big Data Analytics: The Future of Insights",
    video: "/video/blog/blog-1.mp4",
    paragraph: "Big data helps businesses make informed decisions...",
    tags: ["Big Data"],
    publishDate: "2024-12-06",
    author: {
      name: "Sophia Martinez",
      designation: "Data Scientist",
      image: "/images/blog/author-06.png",
    },
  },
  {
    id: 7,
    title: "Cloud Computing: A Game Changer",
    video: "/video/blog/blog-1.mp4",
    paragraph: "Cloud technology is transforming industries...",
    tags: ["Cloud Computing"],
    publishDate: "2024-12-07",
    author: {
      name: "Daniel Wilson",
      designation: "Cloud Architect",
      image: "/images/blog/author-07.png",
    },
  },
  {
    id: 8,
    title: "The Evolution of Mobile App Development",
    video: "/video/blog/blog-1.mp4",
    paragraph: "Mobile apps are evolving with new frameworks...",
    tags: ["Mobile Apps"],
    publishDate: "2024-12-08",
    author: {
      name: "Olivia Thomas",
      designation: "App Developer",
      image: "/images/blog/author-08.png",
    },
  },
  {
    id: 9,
    title: "AI and Ethics: A Balancing Act",
    video: "/video/blog/blog-1.mp4",
    paragraph: "Ethical AI development is crucial for fairness...",
    tags: ["AI", "Ethics"],
    publishDate: "2024-12-09",
    author: {
      name: "James Lee",
      designation: "AI Researcher",
      image: "/images/blog/author-09.png",
    },
  },
  {
    id: 10,
    title: "5G and the Future of Connectivity",
    video: "/video/blog/blog-1.mp4",
    paragraph: "5G networks are unlocking new possibilities...",
    tags: ["5G", "Connectivity"],
    publishDate: "2024-12-10",
    author: {
      name: "Emma Garcia",
      designation: "Network Engineer",
      image: "/images/blog/author-10.png",
    },
  },
  {
    id: 11,
    title: "Machine Learning in Healthcare",
    video: "/video/blog/blog-1.mp4",
    paragraph: "ML is revolutionizing medical diagnosis...",
    tags: ["Machine Learning", "Healthcare"],
    publishDate: "2024-12-11",
    author: {
      name: "Liam Robinson",
      designation: "ML Engineer",
      image: "/images/blog/author-11.png",
    },
  },
  {
    id: 12,
    title: "The Metaverse: A New Digital Frontier",
    video: "/video/blog/blog-1.mp4",
    paragraph: "The metaverse is shaping digital interactions...",
    tags: ["Metaverse", "VR"],
    publishDate: "2024-12-12",
    author: {
      name: "Isabella Clark",
      designation: "VR Developer",
      image: "/images/blog/author-12.png",
    },
  },
  {
    id: 12,
    title: "The Metaverse: A New Digital Frontier",
    video: "/video/blog/blog-1.mp4",
    paragraph: "The metaverse is shaping digital interactions...",
    tags: ["Metaverse", "VR"],
    publishDate: "2024-12-12",
    author: {
      name: "Isabella Clark",
      designation: "VR Developer",
      image: "/images/blog/author-12.png",
    },
  },
  {
    id: 13,
    title: "The Metaverse: A New Digital Frontier",
    video: "/video/blog/blog-1.mp4",
    paragraph: "The metaverse is shaping digital interactions...",
    tags: ["Metaverse", "VR"],
    publishDate: "2024-12-12",
    author: {
      name: "Isabella Clark",
      designation: "VR Developer",
      image: "/images/blog/author-12.png",
    },
  },
];

export default blogData;
