import { Blog } from "@/types/blog";

const blogData: Blog[] = [
  {
    id: 1,
    title: "Exploring the Future of AI",
    video: "/video/Blog/blog-1.mp4",
    paragraph: "Cloud computing has revolutionized data storage...",
    tags: ["AI"],
    publishDate: "2024-12-01",
    author: {
      name: "John Doe",
      designation: "Tech Writer",
      image: "/images/blog/author-01.png",
    },
  },
  {
    id: 2,
    title: "The Rise of Cloud Computing",
    video: "/video/Blog/blog-2.mp4",
    paragraph: "Cloud computing has revolutionized data storage...",
    tags: ["Cloud"],
    publishDate: "2024-11-15",
    author: {
      name: "Jane Smith",
      designation: "Cloud Expert",
      image: "/images/blog/author-02.png",
    },
  },
  {
    id: 3,
    title: "Power of Data Science",
    video: "/video/Blog/blog-3.mp4",
    paragraph: "Data Science is transforming industries...",
    tags: ["Data Science"],
    publishDate: "2024-11-20",
    author: {
      name: "Alice Johnson",
      designation: "Data Scientist",
      image: "/images/blog/author-03.png",
    },
  },
  {
    id: 4,
    title: "Machine Learning Applications",
    video: "/video/Blog/blog-4.mp4",
    paragraph: "Machine learning is driving automation...",
    tags: ["ML"],
    publishDate: "2024-10-30",
    author: {
      name: "Robert Brown",
      designation: "ML Engineer",
      image: "/images/blog/author-04.png",
    },
  },
  {
    id: 5,
    title: "Cybersecurity Trends in 2024",
    video: "/video/Blog/blog-5.mp4",
    paragraph: "Cyber threats are evolving rapidly...",
    tags: ["Cybersecurity"],
    publishDate: "2024-09-25",
    author: {
      name: "Emily White",
      designation: "Cybersecurity Analyst",
      image: "/images/blog/author-05.png",
    },
  },
  {
    id: 6,
    title: "Blockchain & Cryptocurrency",
    video: "/video/Blog/blog-6.mp4",
    paragraph: "Blockchain technology is reshaping finance...",
    tags: ["Blockchain"],
    publishDate: "2024-08-10",
    author: {
      name: "David Lee",
      designation: "Blockchain Developer",
      image: "/images/blog/author-06.png",
    },
  },
  {
    id: 7,
    title: "The Future of Quantum Computing",
    video: "/video/Blog/blog-7.mp4",
    paragraph: "Quantum computing is set to revolutionize processing power...",
    tags: ["Quantum Computing"],
    publishDate: "2024-07-15",
    author: {
      name: "Sophia Martinez",
      designation: "Quantum Researcher",
      image: "/images/blog/author-07.png",
    },
  },
  {
    id: 8,
    title: "Web3 and Decentralization",
    video: "/video/Blog/blog-8.mp4",
    paragraph: "Web3 promises a decentralized internet...",
    tags: ["Web3"],
    publishDate: "2024-06-05",
    author: {
      name: "Michael Chen",
      designation: "Web3 Developer",
      image: "/images/blog/author-08.png",
    },
  },
  {
    id: 9,
    title: "Internet of Things (IoT) Innovations",
    video: "/video/Blog/blog-9.mp4",
    paragraph: "IoT is connecting the world like never before...",
    tags: ["IoT"],
    publishDate: "2024-05-20",
    author: {
      name: "Jessica Brown",
      designation: "IoT Specialist",
      image: "/images/blog/author-09.png",
    },
  },
  {
    id: 10,
    title: "Advancements in 5G Technology",
    video: "/video/Blog/blog-10.mp4",
    paragraph: "5G is enabling ultra-fast communication...",
    tags: ["5G"],
    publishDate: "2024-04-10",
    author: {
      name: "Mark Wilson",
      designation: "Network Engineer",
      image: "/images/blog/author-10.png",
    },
  },
];

export default blogData;
